# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
#matrix:
#  include:
#    - python:2.7
#    - python:3.6
services:
  - neo4j

notifications:
  webhooks:
    - https://outlook.office.com/webhook/79cf3255-ca8f-4930-9989-b8d90d179e79@35161fde-e1d6-42a9-b4c5-5feca512255d/TravisCI/7d7f7e85de3a4f8eb47ca357b1d7a7ab/0954b8aa-0448-4e7f-ae89-5907048a7c8c

#warnings_are_errors: false
before_install:
  - pip install --user neo4j-driver
  - pip install --user pandas
#r_packages:
#  - covr

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
