# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
#matrix:
#  include:
#    - python:2.7
#    - python:3.6
services:
  - neo4j
#warnings_are_errors: false
before_install:
  - pip install --user neo4j-driver
  - pip install --user pandas
#r_packages:
#  - covr

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
