---
title: "Neo4j Bolt Driver 1.6 for R"
author: "Brett Taylor"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

 

## Quick Example

```{python eval=TRUE, include=TRUE}
from neo4j.v1 import GraphDatabase
import os


uri = os.environ['NEO4J_URI']
pswd = os.environ['NEO4J_PSWD']
uid = os.environ['NEO4J_USER']

driver = GraphDatabase.driver(uri, auth=(uid, pswd))

def print_friends_of(tx, name):
    for record in tx.run("MATCH (a:Person)-[:KNOWS]->(f) "
                         "WHERE a.name = {name} "
                         "RETURN f.name", name=name):
      print(record["f.name"])

with driver.session() as session:
    session.read_transaction(print_friends_of, "Alice")
```

Convert this to R

```{r eval=FALSE, error=FALSE,message=TRUE, warning=FALSE, include=TRUE}
library(Neo4jDriveR)
uri = "bolt://172.20.0.1:7687"
driver = GraphDatabase$driver(uri, auth=c("neo4j", "neo4j_is_nice"))
print_friends_of <- function(tx, name){
  records <- tx$run("MATCH (a:Person)-[:KNOWS]->(f)
                    WHERE a.name = {name}
                    RETURN f.name", name=name)
  
}

session <- driver.session()
session$read_transaction(print_friends_of, "Alice")
```

Next Generation of R  - To make it useable by a data scientist

```{r eval=FALSE, error=FALSE,message=TRUE, warning=FALSE, include=TRUE}
library(Neo4jDriveR)

uri = "bolt://172.20.0.1:7687"
driver <- graph_driver(uri, user_id = "neo4j", password = "neo4j_is_nice")
print_friends_of <- function(tx, name){
  records <- graph_run(tx, "MATCH (a:Person)-[:KNOWS]->(f)
                    WHERE a.name = {name}
                    RETURN f.name", name=name)
  records
  
}

session <- graph_session(driver)
results <- graph_read_transaction(session, print_friends_of, "Alice")
print(results)

```


## Installation


## API Documentation

To install the latest stable version, use:

```{r}
install.packages("Neo4jDriveR")
```
## Other Information
